"""
train.py
========
Trains 6 phishing-detection models and saves them to src/models/artifacts/.

Unified data pipeline — ALL models train on features derived from the
same source dataset (phishing_site_urls.csv via extracted_features.parquet).

Dataset layout expected in data/:
  data/phishing_site_urls.csv         → columns: URL, Label  (549k rows)
  data/extracted_features.parquet     → 22 URL-derived features + label
      (generated by: python extract_features.py)

Model split:
  Structured ML (trained on 22 URL-derived features):
    → rf.pkl   Random Forest
    → xgb.pkl  XGBoost
    → svm.pkl  Support Vector Machine

  Multimodal Deep Learning (char-level text + same 22 tabular features):
    → lstm.pt        Bidirectional LSTM + TabularBranch
    → cnn.pt         Character-level CNN + TabularBranch
    → transformer.pt Transformer encoder + TabularBranch

Also saves:
  scaler.pkl         StandardScaler for URL features (used by all models)
  feature_cols.pkl   List of feature column names (= URL_FEATURE_NAMES)
  fusion_weights.pkl Dict of model_name → float weight (F1-based)

Usage:
  python train.py [--features data/extracted_features.parquet]
                  [--csv data/phishing_site_urls.csv]
                  [--sample 50000]
                  [--epochs 10]
                  [--device cpu]
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

# Project imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.features import (
    URL_FEATURE_NAMES, extract_url_features, url_to_ids,
    VOCAB_SIZE, MAX_URL_LEN,
)
from src.models.dl_models import (
    URLLSTMClassifier, URLCNNClassifier, URLTransformerClassifier,
    URLDataset,
)

# ── Paths ────────────────────────────────────────────────────────
ROOT      = Path(__file__).resolve().parent
ARTIFACTS = ROOT / "src" / "models" / "artifacts"
ARTIFACTS.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ────────────────────────────────────────────────────────────────
# Data loading (unified pipeline)
# ────────────────────────────────────────────────────────────────

def load_features(path: str, sample: int = 50_000) -> tuple[np.ndarray, np.ndarray, list[str], list[str]]:
    """
    Load pre-extracted features from parquet or CSV.

    Returns:
        X       : float32 array [N, 22] — feature matrix
        y       : int array [N]         — labels (0=benign, 1=phishing)
        urls    : list[str]             — raw URL strings
        feature_cols : list[str]        — feature column names
    """
    log.info(f"  Loading features from {path}…")
    if path.endswith(".parquet"):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    # Sample if needed (stratified)
    if sample and len(df) > sample:
        df = df.groupby("label", group_keys=False).apply(
            lambda g: g.sample(n=min(len(g), int(sample * len(g) / len(df))),
                               random_state=42)
        ).reset_index(drop=True)
        log.info(f"  Sampled to {len(df):,} rows")

    feature_cols = URL_FEATURE_NAMES
    X = df[feature_cols].values.astype(np.float32)
    y = df["label"].values.astype(int)
    urls = df["url"].tolist()

    return X, y, urls, feature_cols


# ────────────────────────────────────────────────────────────────
# DL training loop (multimodal)
# ────────────────────────────────────────────────────────────────

def train_dl_model(
    model: nn.Module,
    train_ids: list[list[int]],
    train_tab: np.ndarray,
    train_labels: list[int],
    val_ids: list[list[int]],
    val_tab: np.ndarray,
    val_labels: list[int],
    epochs: int,
    batch_size: int,
    lr: float,
    device: torch.device,
    name: str,
) -> nn.Module:
    train_ds  = URLDataset(train_ids, train_tab, train_labels)
    val_ds    = URLDataset(val_ids,   val_tab,   val_labels)
    train_dl  = DataLoader(train_ds, batch_size=batch_size, shuffle=True,  num_workers=0)
    val_dl    = DataLoader(val_ds,   batch_size=batch_size, shuffle=False, num_workers=0)

    model     = model.to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer, max_lr=lr, steps_per_epoch=len(train_dl), epochs=epochs
    )
    criterion = nn.BCEWithLogitsLoss()
    best_val_loss = float("inf")
    best_state    = None

    for epoch in range(1, epochs + 1):
        # Train
        model.train()
        total_loss = 0.0
        for xb, tab_b, yb in train_dl:
            xb, tab_b, yb = xb.to(device), tab_b.to(device), yb.to(device)
            optimizer.zero_grad()
            logits = model(xb, tab_b)
            loss   = criterion(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            total_loss += loss.item()

        # Validate
        model.eval()
        val_loss = 0.0
        all_preds, all_labels = [], []
        with torch.no_grad():
            for xb, tab_b, yb in val_dl:
                xb, tab_b, yb = xb.to(device), tab_b.to(device), yb.to(device)
                logits = model(xb, tab_b)
                val_loss += criterion(logits, yb).item()
                preds = (torch.sigmoid(logits) > 0.5).cpu().numpy()
                all_preds.extend(preds)
                all_labels.extend(yb.cpu().numpy())

        f1 = f1_score(all_labels, all_preds, zero_division=0)
        log.info(
            f"  [{name}] epoch {epoch:2d}/{epochs}  "
            f"train_loss={total_loss/len(train_dl):.4f}  "
            f"val_loss={val_loss/len(val_dl):.4f}  "
            f"val_f1={f1:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state    = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    model.load_state_dict(best_state)
    return model


def dl_predict_proba(
    model: nn.Module,
    ids: list[list[int]],
    tab_features: np.ndarray,
    device: torch.device,
    batch_size: int = 512,
) -> np.ndarray:
    model.eval()
    ds     = URLDataset(ids, tab_features, [0] * len(ids))
    dl     = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=0)
    probs  = []
    with torch.no_grad():
        for xb, tab_b, _ in dl:
            xb    = xb.to(device)
            tab_b = tab_b.to(device)
            logits = model(xb, tab_b)
            probs.extend(torch.sigmoid(logits).cpu().numpy())
    return np.array(probs)


# ────────────────────────────────────────────────────────────────
# Main training routine
# ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Train all phishing-detection models")
    parser.add_argument("--features", default="data/extracted_features.parquet",
                        help="Path to pre-extracted features (parquet or CSV)")
    parser.add_argument("--csv",      default="data/phishing_site_urls.csv",
                        help="Path to raw URL CSV (for char tokenization)")
    parser.add_argument("--sample",   type=int, default=50_000)
    parser.add_argument("--epochs",   type=int, default=10)
    parser.add_argument("--batch",    type=int, default=256)
    parser.add_argument("--lr",       type=float, default=3e-4)
    parser.add_argument("--device",   default="cpu")
    args = parser.parse_args()

    device = torch.device(args.device)
    log.info("=" * 60)
    log.info("  PHISHING DETECTOR — UNIFIED TRAINING PIPELINE")
    log.info("=" * 60)

    # ── 1. Load unified features ─────────────────────────────────
    log.info("[1/4] Loading unified feature dataset…")
    X_feat, y, urls, feature_cols = load_features(args.features, sample=args.sample)
    log.info(f"  Dataset: {X_feat.shape}  phishing={y.mean():.1%}")
    log.info(f"  Features: {len(feature_cols)} ({', '.join(feature_cols[:5])}…)")

    # ── 2. Train/test split (shared across all models) ───────────
    log.info("[2/4] Splitting data…")
    (X_tr, X_te, y_tr, y_te,
     urls_tr, urls_te) = train_test_split(
        X_feat, y, urls,
        test_size=0.2, random_state=42, stratify=y,
    )
    log.info(f"  Train: {len(X_tr):,}  Test: {len(X_te):,}")

    # Scale features (single scaler for all models)
    scaler = StandardScaler()
    X_tr_sc = scaler.fit_transform(X_tr)
    X_te_sc = scaler.transform(X_te)

    # Save scaler and feature columns
    joblib.dump(scaler, ARTIFACTS / "scaler.pkl")
    joblib.dump(feature_cols, ARTIFACTS / "feature_cols.pkl")

    # ── 3. Train structured ML models ────────────────────────────
    log.info("[3/4] Training structured ML models (RF / XGB / SVM)…")

    smote = SMOTE(random_state=42)
    X_bal, y_bal = smote.fit_resample(X_tr_sc, y_tr)
    log.info(f"  After SMOTE: {Counter(y_bal)}")

    ml_results: dict[str, dict] = {}

    for name, clf in [
        ("rf",  RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)),
        ("xgb", XGBClassifier(n_estimators=200, eval_metric="logloss", verbosity=0, random_state=42)),
        ("svm", SVC(kernel="rbf", probability=True, C=1.0, random_state=42)),
    ]:
        t0 = time.time()
        clf.fit(X_bal, y_bal)
        y_pred = clf.predict(X_te_sc)
        y_prob = clf.predict_proba(X_te_sc)[:, 1]
        f1  = f1_score(y_te, y_pred)
        auc = roc_auc_score(y_te, y_prob)
        log.info(f"  {name:4s}  F1={f1:.4f}  AUC={auc:.4f}  ({time.time()-t0:.1f}s)")
        ml_results[name] = {"f1": f1, "auc": auc}
        joblib.dump(clf, ARTIFACTS / f"{name}.pkl")

    # ── 4. Train multimodal DL models ────────────────────────────
    log.info("[4/4] Training multimodal DL models (LSTM / CNN / Transformer)…")

    # Character tokenization for text branch
    tr_ids = [url_to_ids(u) for u in urls_tr]
    te_ids = [url_to_ids(u) for u in urls_te]

    # Scaled features for tabular branch (same scaler as ML)
    tr_tab = X_tr_sc.astype(np.float32)
    te_tab = X_te_sc.astype(np.float32)

    tr_lbl = [int(yi) for yi in y_tr]
    te_lbl = [int(yi) for yi in y_te]

    n_tab = len(feature_cols)
    dl_models = {
        "lstm":        URLLSTMClassifier(n_tab_features=n_tab),
        "cnn":         URLCNNClassifier(n_tab_features=n_tab),
        "transformer": URLTransformerClassifier(n_tab_features=n_tab),
    }

    dl_results: dict[str, dict] = {}
    for name, model in dl_models.items():
        log.info(f"  Training {name}…")
        trained = train_dl_model(
            model, tr_ids, tr_tab, tr_lbl, te_ids, te_tab, te_lbl,
            epochs=args.epochs, batch_size=args.batch,
            lr=args.lr, device=device, name=name,
        )
        probs  = dl_predict_proba(trained, te_ids, te_tab, device)
        preds  = (probs > 0.5).astype(int)
        f1  = f1_score(te_lbl, preds)
        auc = roc_auc_score(te_lbl, probs)
        log.info(f"  {name:12s}  F1={f1:.4f}  AUC={auc:.4f}")
        dl_results[name] = {"f1": f1, "auc": auc}
        torch.save(trained.state_dict(), ARTIFACTS / f"{name}.pt")

    # ── Fusion weights (F1-proportional) ─────────────────────────
    all_results = {**ml_results, **dl_results}
    total_f1    = sum(v["f1"] for v in all_results.values())
    weights     = {k: v["f1"] / total_f1 for k, v in all_results.items()}
    joblib.dump(weights, ARTIFACTS / "fusion_weights.pkl")

    log.info("\n" + "=" * 60)
    log.info("  TRAINING COMPLETE")
    log.info("=" * 60)
    for k, v in all_results.items():
        w = weights[k]
        log.info(f"  {k:14s}  F1={v['f1']:.4f}  AUC={v['auc']:.4f}  weight={w:.3f}")
    log.info(f"\n  Artifacts saved → {ARTIFACTS}")


if __name__ == "__main__":
    main()
